# Generated by Django 3.2.10 on 2024-04-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Striming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Platform', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=78)),
                ('Site_link', models.URLField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(max_length=50)),
                ('Ratting', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('Story_line', models.CharField(max_length=500)),
                ('Type', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
