# Generated by Django 3.2.10 on 2024-04-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_list', '0002_auto_20240409_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='Postal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App_list.striming'),
            preserve_default=False,
        ),
    ]
