# Generated by Django 3.2.10 on 2024-04-09 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_list', '0003_watchlist_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='Postal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WatchList', to='App_list.striming'),
        ),
    ]
