# Generated by Django 3.2.10 on 2024-04-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_list', '0006_public_public_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='Avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='Ratting',
            field=models.IntegerField(default=0),
        ),
    ]
