# Generated by Django 3.2.10 on 2024-04-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_list', '0008_auto_20240412_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='Public_user',
        ),
    ]
