# Generated by Django 3.2.10 on 2024-04-16 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_list', '0009_remove_public_public_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='Public_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
