# Generated by Django 3.2.10 on 2024-04-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_list', '0010_public_public_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='Public_user',
        ),
    ]
